/hst:hst/hst:configurations/hippogogreen_nl/hst:workspace/hst:sitemenus/mainnavigation/Producten:
  .meta:order-before: Over Ons
  jcr:primaryType: hst:sitemenuitem
  hst:parameternames: [subname]
  hst:parametervalues: [Ontdek]
  hst:referencesitemapitem: producten
