definitions:
  config:
    /hippo:namespaces/myproject/productcollection:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: [ 'editor:editable', 'mix:referenceable' ]
      jcr:uuid: 99d1c735-1531-4c2d-9589-765a89a3f7bd
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: [ 'mix:referenceable' ]
        jcr:uuid: 46676713-42f0-4c32-a60c-e30f7a1a644e
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: [ 'hipposysedit:remodel', 'mix:referenceable' ]
          jcr:uuid: b5373449-bdaa-4698-b40f-90915e85f5f4
          hipposysedit:node: true
          hipposysedit:supertype: [ 'myproject:basedocument', 'hippostd:relaxed', 'hippotranslation:translated' ]
          hipposysedit:uri: http://www.myproject.com/myproject/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /searchalgorithm:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: myproject:searchalgorithm
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [ contentblocks-validator ]
          /columns:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:columns
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
          /style:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:style
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
          /fullwidth:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:fullwidth
            hipposysedit:primary: false
            hipposysedit:type: Boolean
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:productcollection
          jcr:mixinTypes: [ 'mix:referenceable' ]
          jcr:uuid: 4f73452e-b03b-44c3-95e0-74dc4046e5f5
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2022-05-04T15:44:25.125+02:00
          hippostdpubwf:lastModificationDate: 2022-05-04T15:44:25.125+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          myproject:columns: '4'
          myproject:fullwidth: false
          myproject:style: default
          myproject:title: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [ mode ]
          frontend:references: [ wicket.model, model.compareTo, engine, validator.id ]
          frontend:services: [ wicket.id, validator.id ]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /searchalgorithm:
            jcr:primaryType: frontend:plugin
            caption: Product Search
            compoundList: myproject:findItemsByCategory,myproject:findItemsByKeyword,myproject:findItemsByProductIDs,myproject:findItemsMoreLikeThis
            contentPickerType: links
            field: searchalgorithm
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              maxitems: 1
          /columns:
            jcr:primaryType: frontend:plugin
            caption: Columns
            field: columns
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              selectable.options: 2,3,4,5,6
          /style:
            jcr:primaryType: frontend:plugin
            caption: Style
            field: style
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              selectable.options: default,carousel
          /fullwidth:
            jcr:primaryType: frontend:plugin
            caption: Full Width
            field: fullwidth
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig






