/hst:hst/hst:configurations/hippogogreen_de/hst:workspace/hst:sitemenus/mainnavigation/Produkte:
  jcr:primaryType: hst:sitemenuitem
  hst:parameternames: [subname]
  hst:parametervalues: [Entdecken]
  hst:referencesitemapitem: produkte
