definitions:
  config:
    /hst:platform/hst:hosts/prod:
      jcr:primaryType: hst:virtualhostgroup
    /hst:hst/hst:hosts/prod:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
