/hst:hst/hst:configurations/mobile/hst:workspace/hst:sitemenus/mobile/Products:
  .meta:order-before: Events
  jcr:primaryType: hst:sitemenuitem
  jcr:uuid: 229b38f2-f945-480f-8244-75b5bc7cc9c2
  hst:referencesitemapitem: products
  /Popular:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: 0b0eb84c-39b0-4c26-a471-a48cf31d22eb
    hst:referencesitemapitem: products/popular
  /Recent:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: 93761e6f-635f-4703-b1fd-79c19a774df8
    hst:referencesitemapitem: products/recent
  /Search:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: 6cf4995e-0618-4b71-b9d7-ff71f991759b
    hst:referencesitemapitem: products/search
