/hst:hst/hst:configurations/mobile_zh/hst:workspace/hst:sitemenus/mobile/產品:
  .meta:order-before: 事件
  jcr:primaryType: hst:sitemenuitem
  jcr:uuid: 4128c46b-1cef-47e3-8739-ace55122ae89
  hst:referencesitemapitem: products
  /流行:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: 7bdbee66-bc9a-41f9-9d80-a945fbd4f6a0
    hst:referencesitemapitem: products/popular
  /最近:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: fa26f0c3-365c-4c07-8390-ed994d89e2fb
    hst:referencesitemapitem: products/recent
  /搜索:
    jcr:primaryType: hst:sitemenuitem
    jcr:uuid: 7e609996-4c6c-43dc-8de9-d1bfb6da1a6f
    hst:referencesitemapitem: products/search
