/content/documents/河马转到绿/products:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'hippo:named', 'mix:referenceable']
  jcr:uuid: 84d6e439-6a58-4887-9d7e-707814a2c659
  hippo:name: "博产品\r\n产品"
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: 35fff2a7-22b7-4423-88dd-aa136f95dffe
  hippotranslation:locale: zh
  /重用:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
    jcr:uuid: 1ab7bcbc-d8bc-4f69-9ad7-0a6c9935b7be
    hippostd:foldertype: [new-translated-folder, new-document]
    hippotranslation:id: b0b52823-1f70-485b-ba72-ecb900174665
    hippotranslation:locale: zh
    /2010:
      jcr:primaryType: hippostd:folder
      jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
      jcr:uuid: ae3bf325-30b3-4cf4-bfbf-465e9ea7c037
      hippostd:foldertype: [new-translated-folder, new-document]
      hippotranslation:id: b3859bec-26fa-4b55-a677-b7cb03d59eca
      hippotranslation:locale: zh
      /07:
        jcr:primaryType: hippostd:folder
        jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
        jcr:uuid: 940f60ce-b171-4479-bbcf-add86fc36232
        hippostd:foldertype: [new-translated-folder, new-document]
        hippotranslation:id: 31a3c3cb-97a6-45ac-b764-9701fe19a075
        hippotranslation:locale: zh
        /可持续木头的ipod音响系统:
          jcr:primaryType: hippo:handle
          jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
          jcr:uuid: 3b88ffac-e0dd-4f1a-868e-5f6240f63e6a
          hippo:name: 可持续木头的iPod音响系统
          /可持续木头的ipod音响系统[1]:
            jcr:primaryType: hippogogreen:product
            jcr:mixinTypes: ['mix:versionable']
            jcr:uuid: 9f866f5e-28bb-4f2b-8ebe-cc8d8c9ac40c
            hippo:availability: [preview]
            hippogogreen:categories: [重用]
            hippogogreen:contentstage: none
            hippogogreen:price: 219.0
            hippogogreen:rating: 0.0
            hippogogreen:summary: Vers公司凭着iPod的声望来制造一个优美、音质完美、环境影响最小的音响系统。该系统由人工林生产的可持续木头制成（无有毒化学品、重金属），是数字音乐的扩音器。每个系统都独一无二、手工完成，需要一周的生产时间。
            hippogogreen:title: 可持续木头的iPod音响系统
            hippogogreen:votes: 0
            hippostd:holder: editor01
            hippostd:state: unpublished
            hippostdpubwf:createdBy: admin
            hippostdpubwf:creationDate: 2010-07-12T15:11:00+02:00
            hippostdpubwf:lastModificationDate: 2011-07-15T11:18:00+02:00
            hippostdpubwf:lastModifiedBy: editor01
            hippotranslation:id: 88dfba73-434b-4136-b654-5457314f51d0
            hippotranslation:locale: zh
            /hippogogreen:description:
              jcr:primaryType: hippostd:html
              hippostd:content: |-
                <html>
                <body>

                <p>音质完美：这系统是“刚性”的，这样保证机壳不会因扬声器的压力而谐振，避免歪曲扬声器自身的自然音质。 <br/>
                Vers机壳比相应的塑料系统厚四倍多，厚度9,5毫米（常规塑料系统厚度2毫米）。 <br/>
                可再生性：Vers产品所采用的桉木松木，都来自工厂附近、当地采购经营的人工林。一个Vers系统80%的习用塑料为木头所代替。另外，包装纸的100%是消费后的回收物，而内部的塑料包装、袋子或为消费后纸所代替，或被完全省用。
                </p>

                </body>
                </html>
            /relateddocs:docs:
              jcr:primaryType: relateddocs:docs
              /relateddocs:reldoc:
                jcr:primaryType: hippo:facetselect
                hippo:docbase: ffa43adb-4cf8-4b62-b6b7-da4fefb15221
                hippo:facets: []
                hippo:modes: []
                hippo:values: []
            /hippogogreen:image[1]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 71ee7fcd-2ff1-4de0-bfe8-4175800bf08f
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[2]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 5637dc20-6ed9-4418-8c99-4b70870d19e3
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[3]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 088123f5-759b-414a-a659-6668537a2b86
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[4]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 278ba984-4cf2-4104-aa9f-36c3a2bce709
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[5]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 881f8556-57c9-4338-9cc6-b741b44d05ad
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:copyright:
              jcr:primaryType: hippogogreen:copyright
              hippogogreen:description: Green Home, Inc.
              hippogogreen:url: http://www.greenhome.com/products/appliances/radios_and_electronics/115714/
          /可持续木头的ipod音响系统[2]:
            jcr:primaryType: hippogogreen:product
            jcr:mixinTypes: ['mix:referenceable']
            jcr:uuid: a3e0277f-8bab-41f4-bf17-65dd798cbafa
            hippo:availability: [live]
            hippogogreen:categories: [重用]
            hippogogreen:contentstage: none
            hippogogreen:price: 219.0
            hippogogreen:rating: 0.0
            hippogogreen:summary: Vers公司凭着iPod的声望来制造一个优美、音质完美、环境影响最小的音响系统。该系统由人工林生产的可持续木头制成（无有毒化学品、重金属），是数字音乐的扩音器。每个系统都独一无二、手工完成，需要一周的生产时间。
            hippogogreen:title: 可持续木头的iPod音响系统
            hippogogreen:votes: 0
            hippostd:state: published
            hippostdpubwf:createdBy: admin
            hippostdpubwf:creationDate: 2010-07-12T15:11:00+02:00
            hippostdpubwf:lastModificationDate: 2011-07-15T11:18:00+02:00
            hippostdpubwf:lastModifiedBy: editor01
            hippostdpubwf:publicationDate: 2014-10-14T15:59:20.147+02:00
            hippotranslation:id: 88dfba73-434b-4136-b654-5457314f51d0
            hippotranslation:locale: zh
            /hippogogreen:description:
              jcr:primaryType: hippostd:html
              hippostd:content: |-
                <html>
                <body>

                <p>音质完美：这系统是“刚性”的，这样保证机壳不会因扬声器的压力而谐振，避免歪曲扬声器自身的自然音质。 <br/>
                Vers机壳比相应的塑料系统厚四倍多，厚度9,5毫米（常规塑料系统厚度2毫米）。 <br/>
                可再生性：Vers产品所采用的桉木松木，都来自工厂附近、当地采购经营的人工林。一个Vers系统80%的习用塑料为木头所代替。另外，包装纸的100%是消费后的回收物，而内部的塑料包装、袋子或为消费后纸所代替，或被完全省用。
                </p>

                </body>
                </html>
            /relateddocs:docs:
              jcr:primaryType: relateddocs:docs
              /relateddocs:reldoc:
                jcr:primaryType: hippo:facetselect
                hippo:docbase: ffa43adb-4cf8-4b62-b6b7-da4fefb15221
                hippo:facets: []
                hippo:modes: []
                hippo:values: []
            /hippogogreen:image[1]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 71ee7fcd-2ff1-4de0-bfe8-4175800bf08f
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[2]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 5637dc20-6ed9-4418-8c99-4b70870d19e3
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[3]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 088123f5-759b-414a-a659-6668537a2b86
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[4]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 278ba984-4cf2-4104-aa9f-36c3a2bce709
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:image[5]:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: 881f8556-57c9-4338-9cc6-b741b44d05ad
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /hippogogreen:copyright:
              jcr:primaryType: hippogogreen:copyright
              hippogogreen:description: Green Home, Inc.
              hippogogreen:url: http://www.greenhome.com/products/appliances/radios_and_electronics/115714/
  /facetedproducts:
    jcr:primaryType: hippofacnav:facetnavigation
    hippo:count: 9
    hippo:docbase: 84d6e439-6a58-4887-9d7e-707814a2c659
    hippofacnav:facetnodenames: [价格, 查看产品, 评价]
    hippofacnav:facets: ['hippogogreen:price$[{name:''¥ 0 - ¥ 25'', resolution:''double'',
        end:25}, {name:''¥ 25 - ¥ 50'', resolution:''double'', begin:25, end:50},
        {name:''¥ 50 - ¥ 100'', resolution:''double'', begin:50, end:100}, {name:''¥
        100 - ¥ 250'', resolution:''double'', begin:100, end:250}, {name:''¥ 250 -
        ¥ 500'', resolution:''double'', begin:250, end:500}, {name:''¥ 500 en meer'',
        resolution:''double'', begin:500}]', 'hippogogreen:categories', 'hippogogreen:rating$[{name:''1星级或以上'',
        resolution:''double'', begin:1}, {name:''2星或以上'', resolution:''double'', begin:2},
        {name:''3星级或以上'', resolution:''double'', begin:3}, {name:''4星级或以上'', resolution:''double'',
        begin:4}, {name:''5星或以上'', resolution:''double'', begin:5, end:6}]']
    hippofacnav:limit: 200
    hippofacnav:skipresultsetfacetsavailable: true
