/hst:hst/hst:configurations/hippogogreen/hst:workspace/hst:sitemenus/mainnavigation/Products:
  .meta:order-before: About
  jcr:primaryType: hst:sitemenuitem
  hst:parameternames: [subname]
  hst:parametervalues: [Discover]
  hst:referencesitemapitem: products
