/hst:hst/hst:blueprints/website/hst:configuration/hst:workspace/hst:sitemenus/sectionsmenu/Products:
  .meta:order-before: About
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: products
