/hst:hst/hst:configurations/hippogogreen_fr/hst:workspace/hst:sitemenus/mainnavigation/Produits:
  .meta:order-before: À propos
  jcr:primaryType: hst:sitemenuitem
  hst:parameternames: [subname]
  hst:parametervalues: [Découvrez]
  hst:referencesitemapitem: produits
