/hst:hst/hst:configurations/hippogogreen_nl/hst:workspace/hst:sitemenus/sectionsmenu/Producten:
  .meta:order-before: Over Ons
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: producten
